### ISSUE TITLE
Show MAC address in WiFi configuration

### ISSUE THREAD

**Issue by RetroTechN00b** [diegoparrilla/atarist-sidecart-raspberry-pico#36]
Some WiFi networks are protected by MAC-address filter. In order to be able to connect to the WiFi network the MAC address of the SidecarT Pi Pico must be added to the allow list. Consequently the WiFi SidecarT configuration should show the MAC address od the Pi Pico.

**Comment by diegoparrilla** [comment]
The forthcoming release v0.0.11 will show the MAC address to the user in the Configurator
