### ISSUE TITLE
STE hanging after boot to desktop with Beta v0.0.12

### ISSUE THREAD

**Issue by PeterHurn** [diegoparrilla/atarist-sidecart-raspberry-pico#62]
STE hanging after boot to desktop with Beta v0.0.12

I have an Atari STE running TOS 1.62, 4Mb Ram

I have updated to v0.0.12 but I now get lockups of system hanging when I get to the desktop, I may be able to move the mouse for a few seconds and then the machine locks up.

I have reverted to 0.0.11 and everything seems ok again.

**Comment by diegoparrilla** [comment]
New memory handling improvements and better memory management in the ST boot process fix problems found as described.
