### ISSUE TITLE
Add a per-country configuration of the Wifi 

### ISSUE THREAD

**Issue by diegoparrilla** [diegoparrilla/atarist-sidecart-raspberry-pico#81]
Acknowledging user feedback on Pico W.'s network coverage issues, particularly in the US, we are introducing a new parameter, `WIFI_COUNTRY`, to improve connectivity. This parameter allows for country-specific Wi-Fi initialization using the ISO 3166-1 alpha-2 country code. If not specified, the default WORLDWIDE setting remains. 
This adjustment aims to optimize performance by addressing the unique network characteristics of different regions.

**Comment by nplanel** [comment]
https://github.com/diegoparrilla/atarist-sidecart-raspberry-pico/pull/83
