### ISSUE TITLE
Dual booting with ADSCSI Hard Drive

### ISSUE THREAD

**Issue by calfranklin0598** [diegoparrilla/atarist-sidecart-raspberry-pico#98]
Is there a way to dual boot SideCarT with my existing ADSCSI Hard Drive?

**Comment by diegoparrilla** [comment]
The Floppy emulator already support boot from hard drive. As a side not, boot from floppy is disabled in TOS when a hard disk is present.

The new GEMdrive hard disk firmware can run alongside with other hard disk drives.
